[METADATA]
modified = 2022-02-03T00:00:00.000Z

[[ACCOUNTS]]
address = "rU5RuywZvguLWY2osbPEBHHU18rLf2Swf4"
desc = "Testnet Wallet #1"
network = "testnet"

[[ACCOUNTS]]
address = "rMp1zbKWYiSVJ535tLjV9B1PaHyXiS5TxU"
desc = "Mainnet Wallet #1"
network = "main"

[[ACCOUNTS]]
address = "r3iKY5HKD2JbWqprgMXgx1VMLNn4dza2We"
desc = "XLS20d Wallet #1"
network = "XLS20d"

[[PRINCIPALS]]
name = "contact us!"
email = "info@aesthetes.art"

[[VALIDATORS]]
public_key = "nHU3AenyRuJ4Yei4YHkh6frZg8y2RwXznkMAomUE1ptV5Spvqsih"
attestation="44317E1F9114A104290B4AD92D84CCFD48B251E36B5B2460B27C13456DC4E2E85527F633817613344CD876984255EE0FCB9637CCE25314D2F1EF8FAFD9B30A02"
network = "main"
owner_country = "it"
server_country = "eu"
unl = "https://vl.xrplf.org"

[URI_RESOLUTION]
list = [
  "https://gateway.pinata.cloud/ipfs/{:cid:}{:path:}",
  "https://ipfs.infura.io/ipfs/{:cid:}{:path:}",
  "https://ipfs.io/ipfs/{:cid:}{:path:}"
]

[IMMUTABLE_SOURCES]
list = [
  "^https:\\/\\/gateway\\.pinata\\.cloud\\/ipfs\\/(\\{:[\\w]+:\\})+$",
  "^https:\\/\\/ipfs\\.infura\\.io\\/ipfs\\/(\\{:[\\w]+:\\})+$",
  "^https:\\/\\/ipfs\\.io\\/ipfs\\/(\\{:[\\w]+:\\})+$"
]


